### PR TITLE
Add Solr 8.8

### PR DESCRIPTION
**Pull request by 1ed**
Closes https://github.com/docker-solr/docker-solr/issues/365

### CODE REVIEW

**Review by henrik242 — APPROVED** [review]

**Comment by 1ed** [comment]
Do I need to add anything else?

**Review by makuk66 — CHANGES_REQUESTED** [review]
You're not meant to check in `upstream-versions`.
`upstream_versions` is in `.gitignore`, but that's obviously a typo.
Can you remove this file from the PR, and fix the `.gitignore` please?

Similarly `ownertrust.txt` should not be checked in.
Can you remove this file from the PR, and add it to the `.gitignore` please?

Normally those files get cleaned up automatically by `update.sh`; which makes me wonder if that completed successfully?

**Comment by 1ed** [comment]
Thank you for the review. 

> Normally those files get cleaned up automatically by `update.sh`; which makes me wonder if that completed successfully?

Indeed, it failed, but I didn't noticed, because it created the 8.8 folder. It should be good now.

**Comment by makuk66** [comment]
> Indeed, it failed

Why? What did it say?

**Comment by 1ed** [comment]
I don't know what was the cause, it was last week, maybe a network or a fingerprint check error when it downloads the releases.

It did run to the end now, and the tests too
```
Completed all tests for dockersolr/docker-solr:8.8
```
But Travis is really slow now, could you please stop this build? https://travis-ci.org/github/docker-solr/docker-solr/builds/758083958

**Comment by 1ed** [comment]
The build is green now.

**Comment by 1ed** [comment]
What do you think about migrating to GitHub Actions? It's much faster and reliable https://github.com/1ed/docker-solr/actions/runs/550626716
The scripts need to be adopted and someone has to setup the environment variables to push the images though.
Maybe good for a different PR?

**Review by makuk66 — APPROVED** [review]

**Comment by makuk66** [comment]
> What do you think about migrating to GitHub Actions?

I think that's a fine idea; but that's up to the Apache maintainers.

**Review by dsmiley — APPROVED** [review]

**Pull request merged**
