### PR TITLE
Added alpine variants

### PR DESCRIPTION
**Pull request by LaurentGoderre**
This creates images half the size of the regular ones

/cc @sylus

### CODE REVIEW

**Comment by makuk66** [comment]
Thanks. I like the idea, but I can't merge that as-is because:
- need a Dockerfile-alpine.template and modify update.sh so that alpine versions get created
- need to modify build-all.sh to build the alpine versions locally
- I expect generate-stackbrew-library.sh needs changing too
- The tar/wget changes -- did you change the argument ordering and short form just as a matter of taste?
- I expect update.md might need some changes, either in steps or in example output

**Comment by LaurentGoderre** [comment]
Fair enough though this outlines how we would get there.

For the wget changes, alpine uses POSIX version of wget so the parameters are different. I modified the call to work with the builtin wget. For the tar, the POSIX was missing some of the option so I downloaded a different one than the default one.

**Comment by LaurentGoderre** [comment]
@makuk66 I will work with you to get this working

**Comment by makuk66** [comment]
Thanks for the info -- I'd like to keep the dockerfiles as same a possible, so we might just backport those changes to the non-apline versions too.

I expect we'll also need to install bash for some of the bin scripts; and we should verify it they still work.

It may keep the scripts cleaner if we keep the alpine versions on the same level rather than subdirectories.

I'll make some time for this on Monday.

**Comment by LaurentGoderre** [comment]
I added bash to the install. 

For the hierarchy, I am doing what I saw done in the java and other images

**Comment by LaurentGoderre** [comment]
Added the template and updated the update.sh

**Comment by sylus** [comment]
This looks awesome to me! The only minor nit is I usually like seeing the packages each on a new line for readability. 

https://github.com/docker-library/php/blob/0d23b3d/5.6/fpm/alpine/Dockerfile#L4

I've also added @ncopa as he is doing all of the other official alpine images for docker-library in case has any points.

**Comment by LaurentGoderre** [comment]
@makuk66 I wonder if this block will work as is for this case (changing the variant names of course)

https://github.com/nodejs/docker-node/blob/master/generate-stackbrew-library.sh#L33-L44

**Comment by LaurentGoderre** [comment]
I regenerated all the dockerfile from the template and updated script. Only need to update the build-all and stackbrew

**Comment by LaurentGoderre** [comment]
Updated the build-all script

**Comment by makuk66** [comment]
The build-all.sh looks good, and works for me.
That generate-stackbrew-library snippet looks good, and works for me.
The update.sh looks good. Just stick a space after that comment #.
I've pushed a change to use the short-form `-O` for wget, to reduce the diff on this end.
The updated alpine tar can use the long form, so switch back to that.

**Comment by LaurentGoderre** [comment]
I made the changes. I haven't done anything for the generate-stackbrew yet though

**Comment by LaurentGoderre** [comment]
Also, some of the scripts don't have the executable mod in the commited files, is that intentional?

**Comment by makuk66** [comment]
Thanks @LaurentGoderre; I've merged.

> Also, some of the scripts don't have the executable mod in the commited files, is that intentional?

No; fixed.

**Pull request merged**
