### PR TITLE
Upgrade to solr 8.8.1

### PR DESCRIPTION
**Pull request by tkaessmann**
Here is the update to the newest Solr 8.8.1 version.

### CODE REVIEW

**Review by makuk66 — APPROVED** [review]

**Comment by dsmiley** [comment]
Hmmm.... unclear why so many of the build envs failed in the test matrix

**Comment by tkaessmann** [comment]
Can you first try to trigger a rebuild on travis?

**Comment by tkaessmann** [comment]
I tried it with debug. It doesn't make sense why the java docker pulls are failing randomly.
Anyone else an idea?

**Comment by tboeghk** [comment]
It seems that the [Docker Hub rate limit is in effect](https://travis-ci.community/t/docker-pull-fails-often/7137). We'll fix the `build_test_push.sh` script to log into Docker Hub before pulling and not before pushing 👍

**Comment by tboeghk** [comment]
Yikes! Now we ran into [Travis Security Restrictions](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions) that invalidates the given security credentials :-/

**Comment by dsmiley** [comment]
I built this and ran all tests locally.  Can you please remove the travis changes from this PR?

**Comment by tkaessmann** [comment]
Done!

**Comment by dsmiley** [comment]
official-images PR: https://github.com/docker-library/official-images/pull/9699

**Pull request merged**
