### PR TITLE
Add Solr 8.6.0

### PR DESCRIPTION
**Pull request by dsmiley**
All tests pass; no changes.
Issue: #328

### CODE REVIEW

**Comment by dsmiley** [comment]
The CI failed in one case because of a transient issue in with "jattach" served by GitHub was under too much load:
```
+ wget -nv https://github.com/apangin/jattach/releases/download/v1.5/jattach
529https://github.com/apangin/jattach/releases/download/v1.5/jattach:
5302020-08-10 22:09:41 ERROR 429: too many requests.
```

**Comment by dsmiley** [comment]
We could consider embedding the binary for 'jattach'; I'm sure it's tiny.  Then, no need to do checksum :-)  CC @janhoy

**Comment by makuk66** [comment]
> The CI failed in one case

I re-ran that one, you're all ✅

**Comment by makuk66** [comment]
I've verified I can `docker pull dockersolr/docker-solr:8.6`. Thanks David!

**Pull request merged**
