### PR TITLE
Upgrading to Solr 8.6.2 (#340)

### PR DESCRIPTION
**Pull request by chatman**
I tested with "cd 8.6; docker build --network=host ." on my Fedora 32 dev box and it succeeded.

(This is my first release here, so please help me out if I missed something).

### CODE REVIEW

**Comment by dsmiley** [comment]
Judging from the wiki page you created, I have a suspicion that you went about this by examining a previous bugfix release commit and reproducing it manually.  Like reverse-engineering in a way.  Just a guess; am I right?  To do releases, the process is already very well documented here: https://github.com/docker-solr/docker-solr/blob/master/update.md

**Comment by chatman** [comment]
Ouch, yes! I didn't know that doc existed. Should I remove the wiki page
contents and point to this document?

And yes, I did use the reverse engineering method based on previous PRs!
I'll now follow this doc.

**Comment by chatman** [comment]
I ran the update.sh script on another branch, and I got the exact same changeset as I got in this PR (by hand) :-)
I'm ready to merge this soon.

**Comment by chatman** [comment]
Merged to master via command line.

**Pull request closed without merging**
